# Generated by Django 6.0.2 on 2026-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
