# Generated by Django 6.0.2 on 2026-03-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tour_image_url_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='badge',
            field=models.CharField(blank=True, help_text='e.g. Best Seller, New, Popular', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(default='Adventure', help_text='e.g. Adventure, Cultural, Trekking, Wildlife, Spiritual, Day Trip', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Challenging', 'Challenging'), ('Extreme', 'Extreme')], default='Moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs, e.g. ["https://…", "https://…"]'),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='Tour highlights, e.g. ["Sunrise view", "Guided trek"]'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.JSONField(blank=True, default=list, help_text='What is included, e.g. ["Hotel pickup", "Meals", "Guide"]'),
        ),
        migrations.AddField(
            model_name='tour',
            name='long_description',
            field=models.TextField(blank=True, help_text='Full description shown on detail page. Separate paragraphs with blank lines.'),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(help_text='Short summary shown on cards (2-3 lines).'),
        ),
    ]
