# Generated by Django 6.0.2 on 2026-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_badge_tour_category_tour_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_latest',
            field=models.BooleanField(default=False, help_text='Show on the home page as a featured latest tour.'),
        ),
    ]
