# Generated by Django 6.0.2 on 2026-05-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tour_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='best_season',
            field=models.CharField(blank=True, default='', help_text="Short label shown next to duration/rating/difficulty on the tour detail page, e.g. 'Best Season: Mar–May, Sep–Nov' or 'Excellent Season'.", max_length=120),
        ),
    ]
