# Generated by Django 6.0.2 on 2026-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_tourfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-filled: translations of text fields into all supported languages.'),
        ),
        migrations.AddField(
            model_name='tourfaq',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
