# Generated by Django 6.0.2 on 2026-04-28 18:15
# Manually edited to handle unique booking_reference population for existing rows.

import secrets

import apps.bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _unique_ref():
    return f"GTN-{secrets.token_hex(4).upper()}"


def populate_booking_references(apps, schema_editor):
    """Assign a unique booking_reference to every existing booking row."""
    TourBooking = apps.get_model("bookings", "TourBooking")
    EventBooking = apps.get_model("bookings", "EventBooking")

    for Model in (TourBooking, EventBooking):
        used = set()
        for obj in Model.objects.filter(booking_reference__isnull=True):
            ref = _unique_ref()
            while ref in used:
                ref = _unique_ref()
            used.add(ref)
            obj.booking_reference = ref
            obj.save(update_fields=["booking_reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_completed_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: add booking_reference as nullable (no index yet — added in Step 3 via unique)
        migrations.AddField(
            model_name='eventbooking',
            name='booking_reference',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='booking_reference',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),

        # Step 2: populate unique values for all existing rows
        migrations.RunPython(populate_booking_references, migrations.RunPython.noop),

        # Step 3: make non-nullable and unique
        migrations.AlterField(
            model_name='eventbooking',
            name='booking_reference',
            field=models.CharField(
                db_index=True,
                default=apps.bookings.models._gen_booking_ref,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='booking_reference',
            field=models.CharField(
                db_index=True,
                default=apps.bookings.models._gen_booking_ref,
                max_length=20,
                unique=True,
            ),
        ),

        # Step 4: add guest fields
        migrations.AddField(
            model_name='eventbooking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),

        # Step 5: make user nullable
        migrations.AlterField(
            model_name='eventbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
