# Generated by Django 6.0.2 on 2026-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_eventbooking_booking_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='special_requests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='special_requests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
