# Generated by Django 6.0.2 on 2026-03-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Get Tours Nepal', max_length=255)),
                ('site_tagline', models.CharField(blank=True, help_text='Brief tagline for the website', max_length=255)),
                ('site_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('logo', models.ImageField(blank=True, help_text='Main site logo', null=True, upload_to='site/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo for dark backgrounds', null=True, upload_to='site/')),
                ('footer_text', models.TextField(blank=True, help_text='Footer copyright and text')),
                ('footer_logo', models.ImageField(blank=True, help_text='Logo for footer', null=True, upload_to='site/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('tiktok_url', models.URLField(blank=True, help_text='TikTok profile URL')),
                ('privacy_policy_url', models.URLField(blank=True, help_text='Privacy policy page URL')),
                ('terms_of_service_url', models.URLField(blank=True, help_text='Terms of service page URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
