# Generated by Django 6.0.2 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_aboutstat_leader_milestone_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="home_portfolio_image_1",
            field=models.ImageField(blank=True, help_text="Homepage portfolio image 1", null=True, upload_to="site/home/"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="home_portfolio_image_2",
            field=models.ImageField(blank=True, help_text="Homepage portfolio image 2", null=True, upload_to="site/home/"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="home_portfolio_image_3",
            field=models.ImageField(blank=True, help_text="Homepage portfolio image 3", null=True, upload_to="site/home/"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="home_portfolio_image_4",
            field=models.ImageField(blank=True, help_text="Homepage portfolio image 4", null=True, upload_to="site/home/"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="home_portfolio_image_5",
            field=models.ImageField(blank=True, help_text="Homepage portfolio image 5", null=True, upload_to="site/home/"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="home_portfolio_link_label",
            field=models.CharField(blank=True, default="View portfolio", max_length=120),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="home_portfolio_link_url",
            field=models.CharField(blank=True, default="/tours", help_text="CTA target for the homepage portfolio collage. Can be an internal path like /tours or an external URL.", max_length=255),
        ),
    ]
