# Generated by Django 6.0.2 on 2026-04-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_siteconfig_home_portfolio_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('tours', 'Tours'), ('events', 'Events'), ('blog', 'Blog'), ('about', 'About'), ('contact', 'Contact'), ('faqs', 'FAQs'), ('booking', 'Booking'), ('booking-policy', 'Booking Policy'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('search', 'Search')], max_length=60, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Short label shown above the title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Longer text shown below the title')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Banner',
                'verbose_name_plural': 'Page Banners',
                'ordering': ['page'],
            },
        ),
    ]
