# Generated by Django 6.0.2 on 2026-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_add_partner_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='category',
            field=models.CharField(choices=[('guide', 'Trail Leader / Guide'), ('team', 'Office Team (CEO / Staff)')], default='guide', help_text="'Trail Leader / Guide' shows in Trail Leaders section. 'Office Team' shows in Meet Our Team section on the About page.", max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='google_map_url',
            field=models.URLField(blank=True, help_text='Google Maps link or embed URL used on the Contact page (paste the share-link or the iframe src URL).', max_length=1000),
        ),
    ]
