# Generated by Django 6.0.2 on 2026-05-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional short description.', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Optional emoji shown on the home 'Find Your Adventure' tile (e.g. 🏔️, 🛕). Used as a fallback when no image is uploaded.", max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text="Optional image shown on the home 'Find Your Adventure' tile. If set, it takes priority over the icon.", null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="If checked, this category shows in the home page 'Find Your Adventure' section (latest 6 featured)."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_eyebrow',
            field=models.CharField(blank=True, default='Who We Are', help_text="Small label shown above the About 'Who We Are' heading.", max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_paragraph_1',
            field=models.TextField(blank=True, default='', help_text='First paragraph under the About heading.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_paragraph_2',
            field=models.TextField(blank=True, default='', help_text='Second paragraph under the About heading.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_title',
            field=models.CharField(blank=True, default='We Make Every Trek Meaningful', help_text="Main heading text in the About 'Who We Are' section.", max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
