# Generated by Django 6.0.2 on 2026-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_siteconfig_home_gallery_images_9_12'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional heading shown above the poster image.', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Event poster image.', null=True, upload_to='popups/')),
                ('button_text', models.CharField(default='View Details', help_text='CTA button label.', max_length=100)),
                ('button_url', models.CharField(blank=True, help_text='URL the button links to (internal path or full URL).', max_length=500)),
                ('is_active', models.BooleanField(default=False, help_text='Show this popup to visitors.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Popup',
                'verbose_name_plural': 'Event Popup',
            },
        ),
    ]
