# Generated by Django 6.0.2 on 2026-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_event_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstat',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Auto-filled: translations of 'label' into all supported languages."),
        ),
        migrations.AddField(
            model_name='leader',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-filled: translations of role & bio.'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Auto-filled: translations of 'text'."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-filled: translations of all editable text fields into supported languages.'),
        ),
        migrations.AddField(
            model_name='value',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-filled: translations of title & description.'),
        ),
    ]
