# Generated by Django 6.0.2 on 2026-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_add_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-filled: translations of name & description.'),
        ),
        migrations.AddField(
            model_name='eventpopup',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-filled: translations of title & button_text.'),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-filled: translations of title, subtitle & description.'),
        ),
    ]
