# Generated by Django 6.0.2 on 2026-03-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(blank=True, help_text='Full article content. Separate paragraphs with blank lines.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Get Tours Team', max_length=100)),
                ('category', models.CharField(default='Travel Tips', max_length=100)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g. Nepal, Trekking', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
