# Generated by Django 6.0.2 on 2026-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-filled: translations of text fields into all supported languages.'),
        ),
    ]
