from django.urls import path
from .views import (
    health_check_view,
    upload_image_view,
    site_config_view,
    site_config_update_view,
    contact_submit_view,
    contact_list_view,
    contact_detail_view,
    newsletter_subscribe_view,
    newsletter_list_view,
    about_stats_list_view,
    about_stat_create_view,
    about_stat_detail_view,
    about_values_list_view,
    about_value_create_view,
    about_value_detail_view,
    about_leaders_list_view,
    about_leader_create_view,
    about_leader_detail_view,
    about_milestones_list_view,
    about_milestone_create_view,
    about_milestone_detail_view,
    page_banners_list_view,
    page_banner_by_page_view,
    page_banner_update_view,
    partners_list_view,
    partner_create_view,
    partner_detail_view,
    categories_list_view,
    category_create_view,
    category_detail_view,
)

urlpatterns = [
    path('health/', health_check_view, name='health-check'),
    path('upload-image/', upload_image_view, name='upload-image'),
    path('config/', site_config_view, name='site-config'),
    path('config/update/', site_config_update_view, name='site-config-update'),
    path('contact/', contact_submit_view, name='contact-submit'),
    path('contact/submissions/', contact_list_view, name='contact-list'),
    path('contact/submissions/<int:pk>/', contact_detail_view, name='contact-detail'),
    path('newsletter/subscribe/', newsletter_subscribe_view, name='newsletter-subscribe'),
    path('newsletter/subscribers/', newsletter_list_view, name='newsletter-list'),
    path('about/stats/', about_stats_list_view, name='about-stats'),
    path('about/stats/create/', about_stat_create_view, name='about-stat-create'),
    path('about/stats/<int:pk>/', about_stat_detail_view, name='about-stat-detail'),
    path('about/values/', about_values_list_view, name='about-values'),
    path('about/values/create/', about_value_create_view, name='about-value-create'),
    path('about/values/<int:pk>/', about_value_detail_view, name='about-value-detail'),
    path('about/leaders/', about_leaders_list_view, name='about-leaders'),
    path('about/leaders/create/', about_leader_create_view, name='about-leader-create'),
    path('about/leaders/<int:pk>/', about_leader_detail_view, name='about-leader-detail'),
    path('about/milestones/', about_milestones_list_view, name='about-milestones'),
    path('about/milestones/create/', about_milestone_create_view, name='about-milestone-create'),
    path('about/milestones/<int:pk>/', about_milestone_detail_view, name='about-milestone-detail'),
    path('banners/', page_banners_list_view, name='page-banners-list'),
    path('banners/<str:page>/', page_banner_by_page_view, name='page-banner-by-page'),
    path('banners/<str:page>/update/', page_banner_update_view, name='page-banner-update'),
    path('partners/', partners_list_view, name='partners-list'),
    path('partners/create/', partner_create_view, name='partner-create'),
    path('partners/<int:pk>/', partner_detail_view, name='partner-detail'),
    path('categories/', categories_list_view, name='categories-list'),
    path('categories/create/', category_create_view, name='category-create'),
    path('categories/<int:pk>/', category_detail_view, name='category-detail'),
]
