from django.db import models
from django.conf import settings
from apps.common.models import TimeStampedModel


class PaymentGateway(models.TextChoices):
    MPG = "MPG", "MPG (Mastercard Payment Gateway)"


class PaymentStatus(models.TextChoices):
    PENDING = "PENDING", "Pending"
    INITIATED = "INITIATED", "Initiated"
    SUCCESS = "SUCCESS", "Success"
    FAILED = "FAILED", "Failed"
    CANCELLED = "CANCELLED", "Cancelled"
    REFUNDED = "REFUNDED", "Refunded"


class PaymentTransaction(TimeStampedModel):
    # Null for guest bookings
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True
    )
    booking_reference = models.CharField(max_length=255, help_text="TourBooking or EventBooking ID")
    booking_type = models.CharField(max_length=20, choices=[("TOUR", "Tour"), ("EVENT", "Event")])

    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=10, default="USD")

    gateway = models.CharField(max_length=50, choices=PaymentGateway.choices)
    transaction_id = models.CharField(max_length=255, unique=True, null=True, blank=True)
    status = models.CharField(max_length=50, default=PaymentStatus.PENDING, choices=PaymentStatus.choices)

    # MPG-specific fields. Nullable to keep other gateways untouched.
    mpg_order_id = models.CharField(max_length=64, unique=True, null=True, blank=True, db_index=True)
    mpg_session_id = models.CharField(max_length=128, null=True, blank=True)
    # successIndicator is generated by MPG when the session is created and is compared
    # against resultIndicator returned in the browser redirect to detect tampering.
    mpg_success_indicator = models.CharField(max_length=64, null=True, blank=True)
    # Last raw response from MPG (RETRIEVE_ORDER / webhook payload). Useful for support & audit.
    gateway_response = models.JSONField(null=True, blank=True)

    class Meta:
        indexes = [
            models.Index(fields=["status", "gateway"]),
            models.Index(fields=["booking_type", "booking_reference"]),
        ]

    def __str__(self):
        user_label = self.user.email if self.user else "guest"
        return f"{self.gateway} Payment #{self.id} [{user_label}] - {self.status}"
