# Generated by Django 6.0.2 on 2026-03-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_image_url_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Culture', help_text='e.g. Music, Culture, Festivals, Food, Sports, Workshops', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='Event highlights, e.g. ["Live music", "Food stalls"]'),
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(blank=True, help_text='Full description for event detail page. Separate paragraphs with blank lines.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Short summary shown on cards (2-3 lines).'),
        ),
    ]
