# Generated by Django 6.0.2 on 2026-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_category_event_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_latest',
            field=models.BooleanField(default=False, help_text='Show on the home page as a featured latest event.'),
        ),
    ]
