# Generated by Django 6.0.2 on 2026-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='Gallery image URLs'),
        ),
    ]
