# Generated by Django 6.0.2 on 2026-03-02 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tour__isnull', False), ('event__isnull', True)), models.Q(('tour__isnull', True), ('event__isnull', False)), _connector='OR'), name='review_must_belong_to_tour_or_event'),
        ),
    ]
