# Generated by Django 6.0.2 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_is_approved"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(tour__isnull=False),
                fields=("user", "tour"),
                name="unique_review_per_user_tour",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(event__isnull=False),
                fields=("user", "event"),
                name="unique_review_per_user_event",
            ),
        ),
    ]
