# Generated by Django 6.0.2 on 2026-03-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_reference', models.CharField(help_text='TourBooking or EventBooking ID', max_length=255)),
                ('booking_type', models.CharField(choices=[('TOUR', 'Tour'), ('EVENT', 'Event')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('NEPAL_BANK', 'Nepal Bank')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
