# Generated by Django 6.0.2 on 2026-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymenttransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('MPG', 'MPG (Mastercard Payment Gateway)')], max_length=50),
        ),
    ]
