# Generated by Django 6.0.2 on 2026-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymenttransaction_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
